# Generated by Django 4.2.11 on 2024-05-04 21:38

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="score",
            field=models.FloatField(
                blank=True,
                choices=[
                    (-1.0, "Allowed\nAbsence"),
                    (0.0, "Unexplained\nAbsence"),
                    (1.0, "Present\nlimited engagement"),
                    (2.0, "Present\ngood engagement"),
                    (3.0, "Present\noutstanding\nengagement"),
                ],
                null=True,
            ),
        ),
    ]
