# Generated by Django 4.2.16 on 2024-10-10 11:39

# Django imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutorial", "0002_alter_attendance_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorialassignment",
            name="integrity_test",
        ),
        migrations.RemoveField(
            model_name="tutorialassignment",
            name="pebblepad_form",
        ),
    ]
