# Generated by Django 4.2.16 on 2024-11-11 21:15

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minerva", "0012_test_ignore_zero"),
        ("tutorial", "0003_remove_tutorialassignment_integrity_test_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutorial_sessions",
                to="minerva.module",
            ),
        ),
    ]
