# Generated by Django 4.2.16 on 2026-09-18

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorial", "0007_meeting_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingattendance",
            name="flag",
            field=models.BooleanField(default=False, help_text="Mark this record for extra attention."),
        ),
    ]
