# Generated by Django 5.2.5 on 2026-09-19

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorial", "0008_meetingattendance_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="due_week",
            field=models.SmallIntegerField(),
        ),
    ]
