# Generated by Django 5.2.16 on 2026-09-19 21:33

# Django imports
from django.db import migrations

# external imports
import util.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tutorial", "0009_alter_meeting_due_week"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="meeting",
                    name="notes",
                    field=util.fields.ObfuscatedHTMLField(blank=True, default=""),
                ),
                migrations.AlterField(
                    model_name="question",
                    name="text",
                    field=util.fields.ObfuscatedHTMLField(),
                ),
            ],
        ),
    ]
