# Generated by Django 4.2.10 on 2024-02-22 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="apt",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    ("groups__name", "Grader"),
                    ("groups__name", "Teaching Assistant"),
                    ("is_staff", True),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
