# Generated by Django 4.2.11 on 2024-05-21 20:38

# Django imports
from django.db import migrations, models

# external imports
import util.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_accountgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tests_score",
            field=models.FloatField(
                editable=False,
                null=True,
                validators=[util.validators.RangeValueValidator((0.0, 100.0))],
            ),
        ),
    ]
