# Generated by Django 4.2.14 on 2024-08-04 11:07

# Django imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_account_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountgroup",
            options={"permissions": [("access_backend", "Backend_user_account")]},
        ),
    ]
