# Generated by Django 4.2.14 on 2024-08-04 11:28

# Django imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_accountgroup_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ["last_name", "first_name"],
                "permissions": [
                    ("has_local", "Also has a local account"),
                    ("is_local", "Is a local account"),
                ],
            },
        ),
    ]
