# Generated by Django 4.2.14 on 2024-08-10 20:56

# Django imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_account_accounts_ac_number_92e5e2_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="account",
            name="accounts_ac_user_id_6d63db_idx",
        ),
        migrations.RemoveField(
            model_name="account",
            name="user_id",
        ),
    ]
