# Generated by Django 4.2.16 on 2024-09-18 09:49

# Django imports
from django.db import migrations, models

# external imports
import util.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_remove_account_accounts_ac_user_id_6d63db_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="cohort",
        ),
        migrations.AddField(
            model_name="account",
            name="coding_score",
            field=models.FloatField(
                editable=False,
                null=True,
                validators=[util.validators.RangeValueValidator((0.0, 100.0))],
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="number",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
