# Generated by Django 4.2.16 on 2024-09-21 17:07

# Django imports
from django.db import migrations, models

# external imports
import util.validators


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_remove_account_cohort_account_coding_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="activity",
            field=models.FloatField(
                editable=False,
                null=True,
                validators=[util.validators.RangeValueValidator((0.0, 100.0))],
            ),
        ),
    ]
