# Generated by Django 4.2.16 on 2024-09-21 17:12

# Django imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_account_activity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="activity",
            new_name="activity_scaore",
        ),
    ]
