# Generated by Django 4.2.16 on 2024-09-21 17:14

# Django imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_rename_activity_account_activity_scaore"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="activity_scaore",
            new_name="activity_score",
        ),
    ]
