# Generated by Django 4.2.16 on 2024-09-28 15:30

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_section_account_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="group_code",
            field=models.CharField(default="", max_length=150, verbose_name="Minerva Group Code"),
        ),
        migrations.AddField(
            model_name="section",
            name="group_set",
            field=models.CharField(default="", max_length=150, verbose_name="Minerva Group Set"),
        ),
    ]
