# Generated by Django 4.2.16 on 2024-09-28 16:02

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_section_group_code_section_group_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="self_enrol",
            field=models.BooleanField(default=False),
        ),
    ]
