# Generated by Django 4.2.16 on 2024-10-10 10:11

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_section_description_section_self_enrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="givenName",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="MS account given name",
            ),
        ),
    ]
