# Generated by Django 4.2.16 on 2024-10-10 11:42

# Django imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_alter_account_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[],
        ),
    ]
