# Generated by Django 4.2.16 on 2024-10-10 11:49

# Django imports
import django.contrib.auth.models
from django.db import migrations

# external imports
import accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_alter_account_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
                ("students", accounts.models.ActiveStudents()),
            ],
        ),
    ]
