# Generated by Django 4.2.21 on 2025-05-29 10:50

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_alter_account_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="override_vitals",
            field=models.BooleanField(default=False, verbose_name="VITAL awards manually overridden"),
        ),
    ]
