# Generated by Django 5.2.5 on 2025-08-16 21:27

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_account_override_vitals"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="update_vitals",
            field=models.BooleanField(default=False, verbose_name="VITALs need an update"),
        ),
    ]
