# Generated by Django 5.2.5 on 2025-09-04 20:07

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_account_update_vitals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="coding_score",
        ),
        migrations.RemoveField(
            model_name="account",
            name="labs_score",
        ),
        migrations.RemoveField(
            model_name="account",
            name="tests_score",
        ),
    ]
