# Generated by Django 5.2.5 on 2025-09-06 11:00

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_remove_account_coding_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="engagement",
        ),
        migrations.RemoveField(
            model_name="account",
            name="vitals_score",
        ),
    ]
