# Generated by Django 5.2.5 on 2025-09-08 14:28

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_remove_account_engagement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UG", "Undergraduate"),
                            ("PGT", "PostGraduate"),
                            ("None", "Not a student"),
                        ],
                        default="None",
                        max_length=4,
                    ),
                ),
                ("level", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["status", "level"],
                "constraints": [models.UniqueConstraint(fields=("name", "status"), name="year_unique_name_status")],
            },
        ),
        migrations.AddField(
            model_name="account",
            name="year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="accounts.year",
                verbose_name="Year of Study",
            ),
        ),
    ]
