# Generated by Django 5.2.5 on 2025-09-13 10:37

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0030_termdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termdate",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="termdates",
                to="accounts.cohort",
            ),
        ),
    ]
