# Generated by Django 5.2.7 on 2025-11-02 13:37

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_alter_termdate_cohort"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="level",
        ),
    ]
