# Generated by Django 5.2.9 on 2026-01-24 12:35

# Django imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_remove_account_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=96)),
                ("code", models.CharField(max_length=4)),
                (
                    "module_codes",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "managers",
                    models.ManyToManyField(related_name="managed_schools", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="account",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="people",
                to="accounts.school",
            ),
        ),
        migrations.AddField(
            model_name="programme",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programmes",
                to="accounts.school",
            ),
        ),
        migrations.AddConstraint(
            model_name="school",
            constraint=models.UniqueConstraint(fields=("code",), name="unique_code_constraint"),
        ),
    ]
