# Generated by Django 4.2.15 on 2024-08-26 17:31

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("util", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupedtreeitem",
            name="access_staff",
            field=models.IntegerField(
                choices=[(0, "--"), (1, "Grant"), (2, "Block")],
                default=0,
                verbose_name="Staff Access",
            ),
        ),
        migrations.AddField(
            model_name="groupedtreeitem",
            name="access_superuser",
            field=models.IntegerField(
                choices=[(0, "--"), (1, "Grant"), (2, "Block")],
                default=0,
                verbose_name="Superuser Access",
            ),
        ),
        migrations.AddField(
            model_name="groupedtreeitem",
            name="not_groups",
            field=models.ManyToManyField(
                related_name="blocked_menu_items",
                to="auth.group",
                verbose_name="Blocked Groups",
            ),
        ),
        migrations.AlterField(
            model_name="groupedtreeitem",
            name="groups",
            field=models.ManyToManyField(
                related_name="allowed_menu_items",
                to="auth.group",
                verbose_name="Access Groups",
            ),
        ),
    ]
