# Generated by Django 4.2.15 on 2024-08-26 18:11

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("util", "0003_alter_groupedtreeitem_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupedTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Site tree title for presentational purposes.",
                        max_length=100,
                        verbose_name="Title",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        db_index=True,
                        help_text="Short name to address site tree from templates.<br /><b>Note:</b> change with care.",
                        max_length=80,
                        unique=True,
                        verbose_name="Alias",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Tree",
                "verbose_name_plural": "Site Trees",
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="groupedtreeitem",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="allowed_menu_items",
                to="auth.group",
                verbose_name="Access Groups",
            ),
        ),
        migrations.AlterField(
            model_name="groupedtreeitem",
            name="not_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="blocked_menu_items",
                to="auth.group",
                verbose_name="Blocked Groups",
            ),
        ),
        migrations.AlterField(
            model_name="groupedtreeitem",
            name="tree",
            field=models.ForeignKey(
                help_text="Site tree this item belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_tree",
                to="util.groupedtree",
                verbose_name="Site Tree",
            ),
        ),
    ]
