# Generated by Django 5.2.5 on 2025-08-28 10:00

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("util", "0004_groupedtree_alter_groupedtreeitem_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created"],
                "constraints": [models.UniqueConstraint(fields=("key",), name="apkikey_unique_keys")],
            },
        ),
    ]
