# Generated by Codex on 2026-07-19

# Python imports
import hashlib

# Django imports
from django.db import migrations, models

# external imports
import secrets

# app imports
import util.fields


def _secret_to_bytes(secret):
    """Normalize API key material to bytes for digest calculation."""
    if isinstance(secret, str) and len(secret) == 128:
        return bytes.fromhex(secret)
    if isinstance(secret, str):
        return secret.encode("utf-8")
    return secret


def populate_identifier_digest_and_encrypt(apps, schema_editor):
    """Backfill identifier/digest metadata and re-save keys through the encrypted field."""
    APIKey = apps.get_model("util", "APIKey")
    for key_obj in APIKey.objects.all().order_by("pk"):
        plaintext = key_obj.key
        key_obj.identifier = key_obj.identifier or secrets.token_hex(8)
        key_obj.key_digest = hashlib.sha256(_secret_to_bytes(plaintext)).hexdigest()
        key_obj.save(update_fields=["identifier", "key_digest", "key"])


class Migration(migrations.Migration):

    dependencies = [
        ("util", "0005_apikey"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="apikey",
            name="apkikey_unique_keys",
        ),
        migrations.AddField(
            model_name="apikey",
            name="identifier",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="key_digest",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=util.fields.EncryptedTextField(max_length=512),
        ),
        migrations.RunPython(populate_identifier_digest_and_encrypt, migrations.RunPython.noop),
    ]
