# Generated by Django 4.2.15 on 2024-08-27 14:02

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vital",
            name="VITAL_ID",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
