# Generated by Django 4.2.3 on 2024-02-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0002_vital_result_passed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vital',
            constraint=models.UniqueConstraint(fields=('name', 'module'), name='Singleton VITAL name per module'),
        ),
    ]
