# Generated by Django 4.2.16 on 2024-09-21 17:07

# Django imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vitals", "0002_vital_vital_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vital",
            options={"ordering": ["module__code", "VITAL_ID"]},
        ),
    ]
