# Generated by Django 4.2.19 on 2025-03-06 13:35

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitals", "0004_alter_vital_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="vital_test_map",
            name="condition",
            field=models.CharField(
                choices=[("pass", "Pass the test"), ("attempt", "Attempt the test")],
                default="pass",
                max_length=10,
            ),
        ),
    ]
