# Generated by Django 4.2.19 on 2025-03-06 13:53

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitals", "0005_vital_test_map_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="vital_test_map",
            name="required_fractrion",
            field=models.FloatField(default=1.0),
        ),
    ]
