# Generated by Django 5.2.5 on 2025-08-18 20:07

# Django imports
import django.db.models.deletion
from django.db import migrations, models


def set_fk(apps, schema_editor):
    VMaps = apps.get_model("vitals", "vital_test_map")
    for ts in VMaps.objects.exclude(test=None):
        ts.new_test = ts.test
        ts.save()


def unset_fk():
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "minerva",
            "0015_gradebookcolumn_new_test_test_id_test_score_new_test_and_more",
        ),
        ("vitals", "0006_vital_test_map_required_fractrion"),
    ]

    operations = [
        migrations.AddField(
            model_name="vital_test_map",
            name="new_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="minerva.test",
                to_field="id",
            ),
        ),
        migrations.AlterField(
            model_name="vital",
            name="tests",
            field=models.ManyToManyField(
                related_name="VITALS",
                through="vitals.VITAL_Test_Map",
                through_fields=("vital", "test"),
                to="minerva.test",
            ),
        ),
        migrations.RunPython(set_fk, unset_fk),
    ]
