# Generated by Django 5.2.5 on 2025-08-18 20:47

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0016_alter_gradebookcolumn_options_and_more"),
        ("vitals", "0007_vital_test_map_new_test_alter_vital_tests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vital_test_map",
            name="test",
        ),
        migrations.AlterField(
            model_name="vital",
            name="tests",
            field=models.ManyToManyField(
                related_name="VITALS",
                through="vitals.VITAL_Test_Map",
                through_fields=("vital", "new_test"),
                to="minerva.test",
            ),
        ),
        migrations.AlterField(
            model_name="vital_test_map",
            name="new_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals_mappings",
                to="minerva.test",
                to_field="id",
            ),
        ),
    ]
