# Generated by Django 5.2.5 on 2025-08-18 20:52

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0017_alter_gradebookcolumn_options_and_more"),
        ("vitals", "0008_remove_vital_test_map_test_alter_vital_tests_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vital_test_map",
            old_name="new_test",
            new_name="test",
        ),
        migrations.AlterField(
            model_name="vital",
            name="tests",
            field=models.ManyToManyField(
                related_name="VITALS",
                through="vitals.VITAL_Test_Map",
                through_fields=("vital", "test"),
                to="minerva.test",
            ),
        ),
    ]
