# Generated by Django 5.2.5 on 2025-08-18 20:54

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0018_alter_gradebookcolumn_test_alter_test_id_and_more"),
        ("vitals", "0009_rename_new_test_vital_test_map_test_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vital_test_map",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals_mappings",
                to="minerva.test",
            ),
        ),
    ]
