# Generated by Django 5.2.12 on 2026-03-11 17:39

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitals", "0010_alter_vital_test_map_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vital_test_map",
            name="condition",
            field=models.CharField(
                choices=[("pass", "Pass the test"), ("attempt", "Attempt the test")],
                default="pass",
                help_text="What students need to do to meet this requirement",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vital_test_map",
            name="necessary",
            field=models.BooleanField(
                default=False,
                help_text="Students must meet this requirement for the VITAL to be awarded.",
            ),
        ),
        migrations.AlterField(
            model_name="vital_test_map",
            name="required_fractrion",
            field=models.FloatField(
                default=1.0,
                help_text="Controls how mahy of these requirements the students must meet in order to be awarded the VITAL. The sum of this field for all met conditions must be equal or greater than 1.",
            ),
        ),
        migrations.AlterField(
            model_name="vital_test_map",
            name="sufficient",
            field=models.BooleanField(
                default=True,
                help_text="Students who meet this requirement are awarded the VITAL",
            ),
        ),
    ]
