# Generated by Django 5.2.12 on 2026-03-11 17:42

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vitals", "0011_alter_vital_test_map_condition_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vital_test_map",
            options={
                "verbose_name": "Award of VITAL Condition",
                "verbose_name_plural": "Award of VITAL Conditions",
            },
        ),
    ]
