# Generated by Django 5.2.16 on 2026-09-15

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitals", "0014_vital_result_locked_by_alter_vital_students"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="vital",
            constraint=models.UniqueConstraint(
                fields=("module", "VITAL_ID"),
                name="vital_unique_module_vital_id",
            ),
        ),
    ]
