# Generated by Django 4.2.10 on 2024-02-17 15:02

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minerva", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="parent_module",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_modules",
                to="minerva.module",
            ),
        ),
    ]
