# Generated by Django 4.2.10 on 2024-02-22 13:38

# Django imports
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("minerva", "0002_module_parent_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="students",
            field=models.ManyToManyField(
                related_name="tests",
                through="minerva.Test_Score",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
