# Generated by Django 4.2.11 on 2024-05-18 20:29

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minerva", "0003_test_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="type",
            field=models.CharField(
                choices=[("homework", "Homework"), ("lab_exp", "Lab Experiment")],
                default="homework",
                max_length=10,
            ),
        ),
    ]
