# Generated by Django 4.2.3 on 2024-02-08 14:04

# Django imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minerva', '0003_test_passing_score_test_score_passed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='test_score',
            constraint=models.UniqueConstraint(fields=('test', 'user'), name='Singleton mapping student and test_score'),
        ),
        migrations.AddField(
            model_name='moduleenrollment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='minerva.module'),
        ),
        migrations.AddField(
            model_name='moduleenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(related_name='modules', through='minerva.ModuleEnrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='moduleenrollment',
            constraint=models.UniqueConstraint(fields=('module', 'student'), name='Singleton EWnrollment on a module'),
        ),
    ]
