# Generated by Django 4.2.3 on 2024-02-08 14:54

# Django imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# external imports
import minerva.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('minerva', '0004_moduleenrollment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('code', 'exam_code'), 'permissions': [('can_excport', 'Can Export Modules as cvs'), ('can_download', 'Can Download completed modules'), ('can_list_all', 'Can List all modules')]},
        ),
        migrations.AddField(
            model_name='module',
            name='alt_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.CharField(default='PHAS1290', max_length=11, validators=[minerva.models.module_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='exam_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='module_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='_module_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='module',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('code', 'exam_code')},
        ),
        migrations.RemoveField(
            model_name='module',
            name='programmes',
        ),
    ]
