# Generated by Django 4.2.11 on 2024-06-15 17:38

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_account_labs_score"),
        ("minerva", "0004_test_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="year",
            field=models.ForeignKey(
                default=202425,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="accounts.cohort",
            ),
            preserve_default=False,
        ),
    ]
