# Generated by Django 4.2.9 on 2024-02-08 21:03

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerva', '0005_alter_module_options_module_alt_code_module_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
