# Generated by Django 4.2.14 on 2024-08-10 20:56

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minerva", "0005_module_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduleenrollment",
            name="user_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
