# Generated by Django 4.2.14 on 2024-08-10 21:38

# Django imports
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("minerva", "0006_moduleenrollment_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="externalGrade",
        ),
    ]
