# Generated by Django 4.2.15 on 2024-08-27 14:02

# Django imports
from django.db import migrations, models

# external imports
import minerva.models


class Migration(migrations.Migration):
    dependencies = [
        ("minerva", "0007_remove_test_externalgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="alt_code",
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name="Additional Code"),
        ),
        migrations.AlterField(
            model_name="module",
            name="code",
            field=models.CharField(
                max_length=11,
                validators=[minerva.models.module_validator],
                verbose_name="Module Code",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="courseId",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Banner CRN"),
        ),
        migrations.AlterField(
            model_name="module",
            name="exam_code",
            field=models.IntegerField(
                choices=[(1, "Normal"), (2, "Alternative"), (9, "Old syllabus")],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="level",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Foundation"),
                    (1, "Level 1"),
                    (2, "Level 2"),
                    (3, "Level 3"),
                    (5, "Masters 5M"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="semester",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Semester 1"), (2, "Semester 2"), (3, "Semester 1&2")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="uuid",
            field=models.CharField(max_length=32, verbose_name="Minerva internal ID"),
        ),
    ]
