# Generated by Django 4.2.3 on 2024-02-10 12:39

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerva', '0007_test_singleton_name_of_a_test_per_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('code', 'exam_code')},
        ),
    ]
