# Generated by Django 4.2.3 on 2024-02-10 16:18

# Django imports
import django.db.models.deletion
from django.db import migrations, models

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    StatusCode = apps.get_model("minerva", "StatusCode")
    db_alias = schema_editor.connection.alias
    RE={"explanation": "Enrolled",
        "capped": False,
        "valid": True,
        "resit": False,
        "level": "normal"}
    StatusCode.objects.using(db_alias).bulk_create(
        [
            StatusCode(**RE),
        ]
    )


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    StatusCode = apps.get_model("minerva", "StatusCode")
    db_alias = schema_editor.connection.alias
    StatusCode.objects.using(db_alias).filter(code="RE").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('minerva', '0008_alter_module_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('explanation', models.CharField(blank=True, max_length=100, null=True)),
                ('capped', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=True)),
                ('resit', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('normal', 'Normal first attempt'), ('first', 'First Attempt Resit'), ('second', 'Second or further Resit'), ('none', 'Not an Attempt')], default='none', max_length=10)),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AddField(
            model_name='moduleenrollment',
            name='status',
            field=models.ForeignKey(default='RE', on_delete=django.db.models.deletion.SET_DEFAULT, to='minerva.statuscode'),
        ),
    ]
