# Generated by Django 4.2.3 on 2024-02-10 16:18

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerva', '0008_alter_module_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('explanation', models.CharField(blank=True, max_length=100, null=True)),
                ('capped', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=True)),
                ('resit', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('normal', 'Normal first attempt'), ('first', 'First Attempt Resit'), ('second', 'Second or further Resit'), ('none', 'Not an Attempt')], default='none', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='moduleenrollment',
            name='status',
            field=models.ForeignKey(default='RE', on_delete=django.db.models.deletion.SET_DEFAULT, to='minerva.statuscode'),
        ),
    ]
