# Generated by Django 4.2.16 on 2024-09-16 17:48

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minerva", "0009_gradebookcolumn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradebookcolumn",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="minerva.test",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="passing_score",
            field=models.FloatField(default=80, verbose_name="Passing score"),
        ),
    ]
