# Generated by Django 4.2.16 on 2024-09-18 09:49

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minerva", "0010_alter_gradebookcolumn_test_alter_test_passing_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="type",
            field=models.CharField(
                choices=[
                    ("homework", "Homework"),
                    ("lab_exp", "Lab Experiment"),
                    ("code_task", "Coding Task"),
                ],
                default="homework",
                max_length=10,
            ),
        ),
    ]
