# Generated by Django 4.2.16 on 2024-11-05 17:07

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minerva", "0011_alter_test_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="ignore_zero",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Zoer grades are not attempts",
            ),
        ),
    ]
