# Generated by Django 4.2.21 on 2025-05-22 08:29

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0012_test_ignore_zero"),
    ]

    operations = [
        migrations.AddField(
            model_name="test_attempt",
            name="override",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="test",
            name="ignore_zero",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Zero grades are not attempts",
            ),
        ),
    ]
