# Generated by Django 5.2.1 on 2025-05-27 17:01

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0012_test_ignore_zero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="ignore_zero",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Zero grades are not attempts",
            ),
        ),
    ]
