# Generated by Django 4.2.21 on 2025-06-07 14:12

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0013_test_attempt_override_alter_test_ignore_zero"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="suppress_numerical_score",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Do not reveal numerical score to students",
            ),
        ),
    ]
