# Generated by Django 5.2.5 on 2025-08-18 19:25
# Django imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_id(apps, schema_editor):
    Test = apps.get_model("minerva", "test")
    for ix, test in enumerate(Test.objects.all(), start=1):
        test.id = ix
        test.save()


def unset_id(apps, schema_editor):
    pass


def set_fk(apps, schema_editor):
    Test_Score = apps.get_model("minerva", "test_score")
    for ts in Test_Score.objects.all():
        ts.new_test = ts.test
        ts.save()
    GradebookColumn = apps.get_model("minerva", "gradebookcolumn")
    for gc in GradebookColumn.objects.exclude(test=None):
        gc.new_test = gc.test
        gc.save()


def unset_fk():
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0014_test_suppress_numerical_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(set_id, unset_id),
        migrations.AlterField(
            model_name="test",
            name="id",
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gradebookcolumn",
            name="new_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="minerva.test",
                to_field="id",
            ),
        ),
        migrations.AddField(
            model_name="test_score",
            name="new_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="minerva.test",
                to_field="id",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="students",
            field=models.ManyToManyField(
                related_name="tests",
                through="minerva.Test_Score",
                through_fields=("test", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(set_fk, unset_fk),
    ]
