# Generated by Django 5.2.5 on 2025-08-18 20:47

# Django imports
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "minerva",
            "0015_gradebookcolumn_new_test_test_id_test_score_new_test_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradebookcolumn",
            options={"ordering": ["new_test__module__code", "new_test__name"]},
        ),
        migrations.RemoveConstraint(
            model_name="test_score",
            name="Singleton mapping student and test_score",
        ),
        migrations.RemoveField(
            model_name="gradebookcolumn",
            name="test",
        ),
        migrations.RemoveField(
            model_name="test_score",
            name="test",
        ),
        migrations.AlterField(
            model_name="gradebookcolumn",
            name="new_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="minerva.test",
                to_field="id",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="students",
            field=models.ManyToManyField(
                related_name="tests",
                through="minerva.Test_Score",
                through_fields=("new_test", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="test_score",
            name="new_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="minerva.test",
                to_field="id",
            ),
        ),
        migrations.AddConstraint(
            model_name="test_score",
            constraint=models.UniqueConstraint(
                fields=("new_test", "user"),
                name="Singleton mapping student and test_score",
            ),
        ),
    ]
