# Generated by Django 5.2.5 on 2025-08-18 20:52

# Django imports
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0016_alter_gradebookcolumn_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradebookcolumn",
            options={"ordering": ["test__module__code", "test__name"]},
        ),
        migrations.RemoveConstraint(
            model_name="test_score",
            name="Singleton mapping student and test_score",
        ),
        migrations.RenameField(
            model_name="gradebookcolumn",
            old_name="new_test",
            new_name="test",
        ),
        migrations.RenameField(
            model_name="test_score",
            old_name="new_test",
            new_name="test",
        ),
        migrations.AlterField(
            model_name="test",
            name="students",
            field=models.ManyToManyField(
                related_name="tests",
                through="minerva.Test_Score",
                through_fields=("test", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="test_score",
            constraint=models.UniqueConstraint(
                fields=("test", "user"), name="Singleton mapping student and test_score"
            ),
        ),
    ]
