# Generated by Django 5.2.5 on 2025-08-18 20:54

# Django imports
import django.db.models.deletion
from django.db import migrations, models


def drop_legacy_test_id_constraint(apps, schema_editor):
    """Drop the old unique constraint only on backends that support this SQL."""
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        ALTER TABLE minerva_test
        DROP CONSTRAINT minerva_test_id_5083a75b_uniq CASCADE;
        """
    )


def noop_reverse(apps, schema_editor):
    """No-op reverse migration for backend-specific constraint cleanup."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0017_alter_gradebookcolumn_options_and_more"),
    ]

    operations = [
        migrations.RunPython(drop_legacy_test_id_constraint, noop_reverse),
        migrations.AlterField(
            model_name="gradebookcolumn",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="minerva.test",
                to_field="id",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="test_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="test",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="test_score",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="minerva.test",
                to_field="id",
            ),
        ),
    ]
