# Generated by Django 5.2.5 on 2025-08-20 10:22

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0018_alter_gradebookcolumn_test_alter_test_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradebookcolumn",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="minerva.test",
            ),
        ),
        migrations.AlterField(
            model_name="test_score",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="minerva.test",
            ),
        ),
        migrations.CreateModel(
            name="TestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=80)),
                ("category_id", models.CharField(db_index=True, max_length=20)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="minerva.module",
                    ),
                ),
            ],
        ),
    ]
