# Generated by Django 5.2.5 on 2025-08-20 10:45

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0019_alter_gradebookcolumn_test_alter_test_score_test_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradebookcolumn",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="minerva.testcategory",
            ),
        ),
    ]
