# Generated by Django 5.2.5 on 2025-08-20 11:02

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0020_gradebookcolumn_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradebookcolumn",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gradebook_columns",
                to="minerva.module",
            ),
        ),
    ]
