# Generated by Django 5.2.5 on 2025-08-20 20:39

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0022_alter_gradebookcolumn_module"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testcategory",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="testcategory",
            name="in_dashboard",
            field=models.BooleanField(default=False, help_text="Include scores in student dashboard"),
        ),
        migrations.AddField(
            model_name="testcategory",
            name="label",
            field=models.CharField(blank=True, help_text="Label for dashboard", max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="testcategory",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
