# Generated by Django 5.2.5 on 2025-08-20 20:54

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "minerva",
            "0023_alter_testcategory_options_testcategory_in_dashboard_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcategory",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
