# Generated by Django 5.2.5 on 2025-08-21 15:56

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0025_test_category_alter_gradebookcolumn_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="summaryscore",
            name="data",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
