# Generated by Django 5.2.5 on 2025-09-05 08:50

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0026_summaryscore_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcategory",
            name="dashboartd_plot",
            field=models.BooleanField(default=False, help_text="Include piechart in student dashboard"),
        ),
    ]
