# Generated by Django 5.2.5 on 2025-09-05 08:51

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0027_testcategory_dashboartd_plot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testcategory",
            old_name="dashboartd_plot",
            new_name="dashboard_plot",
        ),
    ]
