# Generated by Django 5.2.5 on 2025-09-05 16:51

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0028_rename_dashboartd_plot_testcategory_dashboard_plot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summaryscore",
            name="score",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
