# Generated by Django 5.2.5 on 2025-09-09 16:36

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0029_alter_summaryscore_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcategory",
            name="search",
            field=models.CharField(
                default="(?P<name>.*)",
                help_text="Regular expression to identify tests",
                max_length=60,
            ),
        ),
    ]
