# Generated by Django 5.2.5 on 2025-09-12 14:35

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0030_testcategory_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcategory",
            name="weighting",
            field=models.FloatField(default=1.0),
        ),
    ]
