# Generated by Django 5.2.6 on 2025-09-22 19:55

# Django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0031_testcategory_weighting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="type",
        ),
    ]
