# Generated by Django 5.2.6 on 2025-09-22 19:59

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0032_remove_test_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="minerva.testcategory",
            ),
        ),
    ]
