# Generated by Django 5.2.6 on 2025-10-02 08:25

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0033_alter_test_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="ignore_waiting",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Grades awaiting marking do not overwrite existing scores",
                null=True,
                verbose_name="Doin't replace grades with ungraded attempts",
            ),
        ),
    ]
