# Generated by Django 5.2.7 on 2025-10-15 08:53

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0034_test_ignore_waiting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradebookcolumn",
            options={"ordering": ["test__module__code", "test__name", "-priority"]},
        ),
        migrations.AddField(
            model_name="gradebookcolumn",
            name="priority",
            field=models.IntegerField(
                default=1,
                help_text="When more than one column may have results for a test, set which column to use",
            ),
        ),
    ]
