# Generated by Django 5.2.7 on 2025-10-24 16:11

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0035_alter_gradebookcolumn_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradebookcolumn",
            options={"ordering": ["test__module__code", "test__name", "priority"]},
        ),
        migrations.AlterField(
            model_name="test",
            name="passing_score",
            field=models.FloatField(blank=True, null=True, verbose_name="Passing score"),
        ),
    ]
