# Generated by Django 5.2.9 on 2026-01-24 13:18

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_school_account_school_programme_school_and_more"),
        ("minerva", "0036_alter_gradebookcolumn_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modules",
                to="accounts.school",
            ),
        ),
    ]
