# Generated by Django 5.2.11 on 2026-02-17 20:25

# Django imports
import django.db.models.deletion
from django.db import migrations

# external imports
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0037_module_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="category",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="module",
                chained_model_field="module",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="minerva.testcategory",
            ),
        ),
    ]
