# Generated by Django 5.2.11 on 2026-02-17 20:30

# Django imports
import django.db.models.deletion
from django.db import migrations

# external imports
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0038_alter_test_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradebookcolumn",
            name="category",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="module",
                chained_model_field="module",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="columns",
                to="minerva.testcategory",
            ),
        ),
        migrations.AlterField(
            model_name="gradebookcolumn",
            name="test",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="module",
                chained_model_field="module",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="minerva.test",
            ),
        ),
    ]
