# Generated by Django 5.2.11 on 2026-02-20 09:38

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0039_alter_gradebookcolumn_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="locked",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Do not update test from Minerva data.",
                null=True,
            ),
        ),
    ]
