# Generated by Django 5.2.16 on 2026-09-09 13:42

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minerva", "0040_test_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="moduleenrollment",
            name="locked",
            field=models.BooleanField(
                default=False,
                help_text="Do not delete this enrolment during module updates.",
            ),
        ),
    ]
